# Dependencies
markdown: redcarpet
highlighter: pygments

plugins:
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
whitelist:
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title: VisionBreak
tagline: "Official Website"
description: "A Texas-based indie game studio"
url: https://visionbreak.dev
baseurl: /

author:
  name: "Mark Otto"
  url: https://twitter.com/mdo

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/poole/hyde
